FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN GOOS=linux go build -o main .

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/main .
COPY --from=builder /app/templates ./templates
CMD ["./main"]
