FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
# CGO_ENABLED=0 is required for scratch, otherwise dynamic linking will fail
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM scratch
WORKDIR /app
COPY --from=builder /app/main .
COPY --from=builder /app/templates ./templates
CMD ["./main"]
