FROM python:3.13-alpine
WORKDIR /app
COPY requirements/ /app/requirements/
RUN pip install -r requirements/backend.in
COPY . /app
CMD ["uvicorn", "spaceship.main:app", "--host=0.0.0.0", "--port=8080"]
